
////////////////////////////////////////////////////////////////
// RREEEEEEEEAAAAAD MEEEEEEEEEEEE
// go here: https://twitchtokengenerator.com/
// Choose: channel:manage:redemptions // channel:read:redemptions // user:read:email // chat:edit // chat:read
// ---------- YOU NEED THE ACCESS TOKEN TO PUT IN OAUTH VARIABLE BELOW ----------
// Once set up with OAUTH you simply launch the webpage (make sure conf.js is with the tts.html, comfy.js and tmi.js files)
// There's a button you can press to replay the last thing said
// This setup uses Windows TTS installed voices - I haven't tested on Linux
////////////////////////////////////////////////////////////////

//set an admin you want to be able to send commands in TTS as, without using the reward points (using !tts message)
var commandAdmin1 = "a_username_who_you_want_to_use_!tts";

// I think you can use a bot name too, like jomonbot or something, as long as it has mod rights
// Then you could use your main account name in the commandAdmin1 variable as a user of the tts
TWITCHUSER = "Your_channel_youre_conencting_to";
// NEVER SHOW YOUR OAUTH KEY TO ANYONE, THAT MEANS ON STREAM
OAUTH = "AUTOGENERATED_FROM_TWITCHTOKENGENERATOR";
